[deploy]
bucket = 'cfn-artifacts-007'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://eoyebamiji.com'
EnvBackendUrl = 'https://api.eoyebamiji.com'
DDBMessageTable = 'CrdDdb-DynamoDBTable-1C524W35B2EW6'