[deploy]
bucket = 'cfn-artifacts-007'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod' 
GithubRepo = 'EOyebamiji/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-cruddur-artifacts-007"
BuildSpec = 'backend-flask/buildspec.yml'