#! /usr/bin/env bash
set -e # stop the execution of the script if it fails

echo "== Validate =="

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="== Validate =="
printf "${CYAN}== ${LABEL}${NO_COLOR}\n"

FUNC_DIR="/workspace/aws-bootcamp-cruddur-2023/ddb/function"
TEMPLATE_PATH="/workspace/aws-bootcamp-cruddur-2023/ddb/template.yaml"
CONFIG_PATH="/workspace/aws-bootcamp-cruddur-2023/ddb/config.toml"
ARTIFACT_BUCKET="cfn-artifacts-007"

sam validate -t $TEMPLATE_PATH

echo "== Build =="

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="== Build =="
printf "${CYAN}== ${LABEL}${NO_COLOR}\n"
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html
# --use-container
# use container is for building the lambda in a container
# it's still using the runtimes and its not a custom runtime

sam build \
--use-container \
--config-file $CONFIG_PATH \
--template $TEMPLATE_PATH \
--base-dir $FUNC_DIR
#--parameter-overrides

OUTPUT_TEMPLATE_PATH="/workspace/aws-bootcamp-cruddur-2023/.aws-sam/build/packaged.yaml"

echo "== Package =="

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="== Package =="
printf "${CYAN}== ${LABEL}${NO_COLOR}\n"
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-package.html

sam package \
  --s3-bucket $ARTIFACT_BUCKET \
  --config-file $CONFIG_PATH \
  --output-template-file $OUTPUT_TEMPLATE_PATH \
  --template-file $TEMPLATE_PATH \
  --s3-prefix "ddb"

echo "== Deploy =="

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="== Deploy =="
printf "${CYAN}== ${LABEL}${NO_COLOR}\n"

PACKAGED_TEMPLATE_PATH="/workspace/aws-bootcamp-cruddur-2023/.aws-sam/build/packaged.yaml"
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html

sam deploy \
  --template-file $PACKAGED_TEMPLATE_PATH  \
  --config-file $CONFIG_PATH \
  --stack-name "CrdDdb" \
  --tags group=cruddur-ddb \
  --no-execute-changeset \
  --capabilities "CAPABILITY_NAMED_IAM"